accepted = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OFL-1.1",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Ubuntu-font-1.0",
  "Zlib",
]

ignore-build-dependencies = false
ignore-dev-dependencies = true
targets = ["x86_64-pc-windows-msvc"]
