[package]
name = "secure-notes"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
publish = false

[dependencies]
eframe = { version = "=0.35.0", default-features = false, features = ["accesskit", "default_fonts", "glow"] }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
